name: "Terraform CI/CD Proyecto Andes"

on:
  push:
    branches:
      - main  # Se activa cuando subes cambios a la rama principal

jobs:
  terraform:
    name: "Terraform Action"
    runs-on: ubuntu-latest
    
    # Aquí le pasamos la llave secreta que acabas de guardar
    env:
      GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}

    steps:
      - name: "Checkout Code"
        uses: actions/checkout@v4

      - name: "Setup Terraform"
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.7.0"

      - name: "Terraform Init"
        run: terraform init

      - name: "Terraform Plan"
        run: terraform plan -input=false

      - name: "Terraform Apply"
        if: github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve -input=false