name: "Terraform CI/CD Proyecto Andes"

on:
  push:
    branches:
      - main  # Se activa cuando subes cambios a la rama principal

jobs:
  terraform:
    name: "Terraform Action"
    runs-on: ubuntu-latest
    
    # Aquí le pasamos la llave secreta que acabas de guardar
    env:
      GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}

    steps:
      - name: "Checkout Code"
        uses: actions/checkout@v4

      - name: "Setup Terraform"
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.7.0"

      - name: "Terraform Init"
        run: terraform init

      - name: "Terraform Plan"
        run: terraform plan -input=false -var="project_id=${{ secrets.PROJECT_ID }}" -var="db_name=${{ secrets.DB_NAME }}"

      - name: "Terraform Apply"
        if: github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve -input=false -var="project_id=${{ secrets.PROJECT_ID }}" -var="db_name=${{ secrets.DB_NAME }}"

      - name: "Install Cloud SQL Proxy & Postgres Client"
        run: |
          curl -o cloud-sql-proxy https://storage.googleapis.com/cloud-sql-connectors/cloud-sql-proxy/v2.11.0/cloud-sql-proxy.linux.amd64
          chmod +x cloud-sql-proxy
          # Instalamos la herramienta psql para enviar el script
          sudo apt-get update && sudo apt-get install -y postgresql-client

      - name: "Initialize Database Schema (IAM Auth)"
        env:
          # Estas variables sacan los datos de tus Secrets de GitHub
          CONNECTION_NAME: ${{ secrets.INSTANCE_CONNECTION_NAME }}
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_USER: ${{ secrets.DB_USER }}
        run: |
          ./cloud-sql-proxy $CONNECTION_NAME --port 5432 --auto-iam-auth &
          sleep 15
          psql "host=127.0.0.1 user=$DB_USER dbname=$DB_NAME sslmode=disable" -f database/init.sql